version: '3.1'
# Servicios
services:

  reverse-proxy:
    #image: jwilder/nginx-proxy:alpine
    image: nginxproxy/nginx-proxy:alpine
    container_name: Reverse-Proxy
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - /volumes/nginx/certs:/etc/nginx/certs:ro
      - /volumes/nginx/vhostd:/etc/nginx/vhost.d
      - /var/run/docker.sock:/tmp/docker.sock:ro
      
lets-encrypt:
  image: jrcs/letsencrypt-nginx-proxy-companion
  container_name: 'Lets-Encrypt'
  restart: always
  environment:
   - VIRTUAL_HOST=portal-mtw.ddns.net
   - VIRTUAL_PATH=/.well-known
   - NGINX_PROXY_CONTAINER=Reverse-Proxy
  volumes:
   - /volumes/nginx/certs:/etc/nginx/certs
   - /volumes/nginx/vhostd:/etc/nginx/vhost.d
   - /volumes/nginx/html:/usr/share/nginx/html:rw
   - /var/run/docker.sock:/var/run/docker.sock:ro

  portal:
    image: nginx
    #container_name: Portal
    restart: always
    environment:
      - VIRTUAL_HOST=portal-mtw.ddns.net
      - VIRTUAL_PATH=/
      - LETSENCRYPT_HOST=portal-mtw.ddns.net
      - LETSENCRYPT_EMAIL=dan1san_@hotmail.com
    volumes:
      - /volumes/www/portal:/usr/share/nginx/html:ro

  factura:
    image: nginx
    #container_name: Factura
    restart: always
    environment:
      - VIRTUAL_HOST=portal-mtw.ddns.net
      - VIRTUAL_PATH=/factura
      - VIRTUAL_DEST=/
      - LETSENCRYPT_HOST=portal-mtw.ddns.net
      - LETSENCRYPT_EMAIL=dan1san_@hotmail.com
    volumes:
      - /volumes/www/factura:/usr/share/nginx/html:ro

  # ERP
  erp:
    image: httpd
    #container_name: ERP
    restart: always
    environment:
      - VIRTUAL_HOST=portal-mtw.ddns.net
      - VIRTUAL_PATH=/erp
      - VIRTUAL_DEST=/
      - LETSENCRYPT_HOST=portal-mtw.ddns.net
      - LETSENCRYPT_EMAIL=dan1san_@hotmail.com
    volumes:
      - /volumes/www/erp:/usr/local/apache2/htdocs
