
version: '3.1'
# Servicios
services:

  reverse-proxy:
    image: nginxproxy/nginx-proxy:alpine
    container_name: Reverse-Proxy
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - /volumes/nginx/certs:/etc/nginx/certs
      - /volumes/nginx/vhostd:/etc/nginx/vhost.d
      - /volumes/nginx/html:/usr/share/nginx/html:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro

  portal:
    image: nginx
    restart: always
    environment:
      - VIRTUAL_HOST=portal-mtw.ddns.net
      - VIRTUAL_PATH=/
      - VIRTUAL_DEST=/
    volumes:
      - /volumes/www/portal:/usr/share/nginx/html:ro

  factura:
    image: nginx
    restart: always
    environment:
      - VIRTUAL_HOST=portal-mtw.ddns.net
      - VIRTUAL_PATH=/factura
      - VIRTUAL_DEST=/
    volumes:
      - /volumes/www/factura:/usr/share/nginx/html:ro

  # ERP
  erp:
    image: httpd
    restart: always
    environment:
      - VIRTUAL_HOST=portal-mtw.ddns.net
      - VIRTUAL_PATH=/erp
      - VIRTUAL_DEST=/
    volumes:
      - /volumes/www/erp:/usr/local/apache2/htdocs
